spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/meet_me?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: "root"
    password: "1234"
    continueOnError: true
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    hikari:
      connection-test-query: SELECT 1
  #    spring.jpa.hibernate.ddl-auto=update
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 596493257866350
            client-secret: 94406040e61d257c47ec385fc253dc4c
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  resources:
    cache:
      cachecontrol:
        max-age: 30d
    chain:
      strategy:
        content:
          enabled: true
          paths: /css/**

#tabula:
#  clean-up: "0 0 2 ? * SUN"

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE





#server.port=8001
##Data Source Properties
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/meet_me?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=1234
##spring.security.oauth2.client.registration
##spring.datasource.initialization-mode = always
##spring.datasource.data=classpath:insert-data.sql
##JPA Properties
#spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.show_sql=true
#spring.jpa.hibernate.format_sql=true
#spring.jpa.hibernate.use_sql_comments=true
####Logging Levels
## Disable the default loggers
#logging.level.org=WARN
##Show SQL executed with parameter bindings
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor=TRACE
## Spring actuator settings - service monitoring metrics
##management.endpoints.web.base-path=/
#management.endpoints.web.exposure.include=info, health, httptrace, metrics, threaddump, heapdump, shutdown, beans
#management.trace.http.enabled=true
#management.endpoint.health.show-details=always
#info.app.name=Post repository application
#info.app.description=This sample application allows to manage articles and users
#info.app.version=1.0.0
## Spring security - demo only - don't use this in production => get secret from environment variable instead
#jwt.secret=springdata_secret